name: arumakan-emoji
parent: default

matches:
  - trigger: ";hug "
    replace: "ğŸ¤—"

  - trigger: ";blush "
    replace: "ğŸ˜Š"

  - trigger: ";thumbsup "
    replace: "ğŸ‘"

  - trigger: ";muscle "
    replace: "ğŸ’ª"

  - trigger: ";eyes "
    replace: "ğŸ‘€"

  - trigger: ";rage "
    replace: "ğŸ˜¡"

  - trigger: ";innocent "
    replace: "ğŸ˜‡"

  - trigger: ";yum "
    replace: "ğŸ˜‹"

  - trigger: ";sob "
    replace: "ğŸ˜­"

  - trigger: ";cry "
    replace: "ğŸ˜¢"

  - trigger: ";thinking "
    replace: "ğŸ¤”"

  - trigger: ";hamster "
    replace: "ğŸ¹"

  - trigger: ";cat "
    replace: "ğŸ±"

  - trigger: ";rabbit "
    replace: "ğŸ°"

  - trigger: ";star "
    replace: "â­"

  - trigger: ";sun "
    replace: "â˜€ï¸"

  - trigger: ";fire "
    replace: "ğŸ”¥"

  - trigger: ";sweat "
    replace: "ğŸ’¦"

  - trigger: ";tada "
    replace: "ğŸ‰"

  - trigger: ";confetti "
    replace: "ğŸŠ"
